from __future__ import annotations

SPEC_DISPLAY_NAMES = {
    "manufacturer": "Manufacturer",
    "part_number": "Part Number",
    "product_family": "Product Family",
    "product_description": "Product Description",
    "device_type": "Device Type",
    "memory_type": "Memory Type",
    "adc_resolution": "ADC Resolution",
    "dac_resolution": "DAC Resolution",
    "sample_rate": "Sample Rate",
    "single_channel_sample_rate": "Single-Channel Sample Rate",
    "dual_channel_sample_rate": "Dual-Channel Sample Rate",
    "channel_modes": "Channel Modes",
    "channel_count": "Channel Count",
    "input_bandwidth": "Analog Input Bandwidth",
    "usable_input_frequency_range": "Usable Input Frequency Range",
    "analog_input_frequency_range": "Analog Input Frequency Range",
    "full_power_bandwidth": "Full-Power Bandwidth",
    "enob": "ENOB",
    "snr": "SNR",
    "sfdr": "SFDR",
    "converter_architecture": "Converter Architecture",
    "jesd_interface": "JESD Interface",
    "jesd_other_references": "Other JESD References Found",
    "digital_interface": "Digital Interface",
    "serial_lane_rate": "Serial Lane Rate",
    "interface_lane_count": "Lane Count",
    "rf_input_frequency_range": "RF Input Frequency Range",
    "modulation_feature": "Modulation Feature",
    "application_examples": "Application Examples",
    "specialized_application_language": "Specialized Application Language",
    "operating_temperature_range": "Operating Temperature Range",
    "automotive_qualification": "Automotive Qualification",
    "space_qualification": "Space Qualification",
    "military_grade": "Military Language",
    "radiation_tolerance": "Radiation Tolerance",
    "tid_rating": "TID Rating",
    "seu_or_sel": "SEU/SEL Language",
    "ruggedization": "Ruggedization Language",
    "esd_human_body_model": "ESD Human Body Model",
    "security_feature": "Security Feature",
    "cryptographic_algorithm": "Cryptographic Algorithm",
    "package_type": "Package",
    "evaluation_hardware": "Evaluation Hardware",
    "supply_voltage": "Supply Voltage",
    "power_consumption": "Power Consumption",
    "clocking_reference_note": "Clocking/Reference Design Note",
    "document_signal": "Document Signal",
}


def display_name_for_spec_name(name: str) -> str:
    return SPEC_DISPLAY_NAMES.get(
        name,
        name.replace("_", " ").title(),
    )
