import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import test,{after,before}from'node:test';
import { LocalStorageDriver } from '../services/storage';import { createSignedInClient } from './helpers/auth';import { assertAuditCount } from './helpers/assertions';import { createArtifactFixture,createDocumentFixture,createRunFixture } from './helpers/fixtures';import { ControlledStorageDriver } from './helpers/storage';import { startHarness,stopHarness,type IntegrationHarness } from './helpers/test-server';
const storage=new ControlledStorageDriver();let h:IntegrationHarness;before(async()=>{h=await startHarness(storage)});after(async()=>{await stopHarness(h)});
async function fixture(label:string){const a=await createSignedInClient(h.baseUrl,h.prisma,label);const d=await createDocumentFixture(h.prisma,a.organization.id);const run=await createRunFixture(h.prisma,a.organization.id,d.id);const artifact=await createArtifactFixture(h.prisma,a.organization.id,run.id,`persisted/${label}.log`);return{a,d,run,artifact};}
test('authorized artifact deletion uses valid CSRF, persisted key, preserves parent and sibling, and audits',async()=>{const{a,run,artifact}=await fixture('artifact-success');const sibling=await createArtifactFixture(h.prisma,a.organization.id,run.id,'persisted/sibling.log');const r=await a.client.request(`/v1/classification-runs/${run.id}/artifacts/${artifact.id}`,{method:'DELETE',csrf:a.csrf,json:{storagePath:'client/evil'}});assert.equal(r.response.status,200);assert.equal(await h.prisma.artifact.findUnique({where:{id:artifact.id}}),null);assert.ok(await h.prisma.classificationRun.findUnique({where:{id:run.id}}));assert.ok(await h.prisma.artifact.findUnique({where:{id:sibling.id}}));assert.equal(storage.attempts.at(-1),'persisted/artifact-success.log');await assertAuditCount(h.prisma,artifact.id,'artifact.deleted',1);});
test('confirmed missing artifact object safely removes metadata',async()=>{storage.enqueue('missing');const{a,run,artifact}=await fixture('artifact-missing');const r=await a.client.request(`/v1/classification-runs/${run.id}/artifacts/${artifact.id}`,{method:'DELETE',csrf:a.csrf});assert.equal(r.response.status,200);assert.equal((r.body as{cleanup:string}).cleanup,'missing');assert.equal(await h.prisma.artifact.findUnique({where:{id:artifact.id}}),null);});
test('artifact deletion has missing invalid and valid CSRF coverage',async()=>{const{a,run,artifact}=await fixture('artifact-csrf');for(const csrf of[undefined,'invalid-token-invalid-token'])assert.equal((await a.client.request(`/v1/classification-runs/${run.id}/artifacts/${artifact.id}`,{method:'DELETE',csrf})).response.status,403);assert.equal((await a.client.request(`/v1/classification-runs/${run.id}/artifacts/${artifact.id}`,{method:'DELETE',csrf:a.csrf})).response.status,200);});
test('artifact route run id must match persisted parent',async()=>{const{a,run,artifact}=await fixture('artifact-parent');const other=await createRunFixture(h.prisma,a.organization.id,run.documentId);assert.equal((await a.client.request(`/v1/classification-runs/${other.id}/artifacts/${artifact.id}`,{method:'DELETE',csrf:a.csrf})).response.status,404);assert.ok(await h.prisma.artifact.findUnique({where:{id:artifact.id}}));});
test('viewer cannot delete artifact',async()=>{const a=await createSignedInClient(h.baseUrl,h.prisma,'artifact-viewer','VIEWER');const d=await createDocumentFixture(h.prisma,a.organization.id);const run=await createRunFixture(h.prisma,a.organization.id,d.id);const artifact=await createArtifactFixture(h.prisma,a.organization.id,run.id);assert.equal((await a.client.request(`/v1/classification-runs/${run.id}/artifacts/${artifact.id}`,{method:'DELETE',csrf:a.csrf})).response.status,403);});
for(const outcome of['timeout','permission_denied','temporary_failure','unknown']as const)test(`artifact ${outcome} records sanitized failure without false success`,async()=>{storage.enqueue(outcome);const{a,run,artifact}=await fixture(`artifact-${outcome}`);const sibling=await createArtifactFixture(h.prisma,a.organization.id,run.id);const r=await a.client.request(`/v1/classification-runs/${run.id}/artifacts/${artifact.id}`,{method:'DELETE',csrf:a.csrf});assert.equal(r.response.status,502);const p=await h.prisma.artifact.findUniqueOrThrow({where:{id:artifact.id}});assert.equal(p.storagePath,artifact.storagePath);assert.equal(p.deletionAttemptCount,1);assert.ok(p.deletionFailureReason);assert.ok(await h.prisma.artifact.findUnique({where:{id:sibling.id}}));await assertAuditCount(h.prisma,artifact.id,'artifact.deletion_failed',1);});
test('retry without persisted cleanup failure returns 409',async()=>{const{a,run,artifact}=await fixture('retry-ineligible');assert.equal((await a.client.request(`/v1/classification-runs/${run.id}/artifacts/${artifact.id}/retry-deletion`,{method:'POST',csrf:a.csrf})).response.status,409);});
for(const outcome of['timeout','temporary_failure']as const)test(`retry after ${outcome} uses persisted metadata and completes cleanup`,async()=>{storage.enqueue(outcome);const{a,run,artifact}=await fixture(`retry-${outcome}`);assert.equal((await a.client.request(`/v1/classification-runs/${run.id}/artifacts/${artifact.id}`,{method:'DELETE',csrf:a.csrf})).response.status,502);storage.enqueue('deleted');const r=await a.client.request(`/v1/classification-runs/${run.id}/artifacts/${artifact.id}/retry-deletion`,{method:'POST',csrf:a.csrf,json:{storagePath:'evil'}});assert.equal(r.response.status,200);assert.equal(await h.prisma.artifact.findUnique({where:{id:artifact.id}}),null);assert.equal(storage.attempts.at(-1),artifact.storagePath);await assertAuditCount(h.prisma,artifact.id,'artifact.deleted',1);});
test('artifact retry has missing invalid and valid CSRF coverage',async()=>{const{a,run,artifact}=await fixture('retry-csrf');await h.prisma.artifact.update({where:{id:artifact.id},data:{deletionFailureReason:'prior failure'}});for(const csrf of[undefined,'invalid-token-invalid-token'])assert.equal((await a.client.request(`/v1/classification-runs/${run.id}/artifacts/${artifact.id}/retry-deletion`,{method:'POST',csrf})).response.status,403);assert.equal((await a.client.request(`/v1/classification-runs/${run.id}/artifacts/${artifact.id}/retry-deletion`,{method:'POST',csrf:a.csrf})).response.status,200);});
test('repeated retry after completed cleanup is safely non-disclosing',async()=>{const{a,run,artifact}=await fixture('retry-repeat');await h.prisma.artifact.update({where:{id:artifact.id},data:{deletionFailureReason:'prior'}});assert.equal((await a.client.request(`/v1/classification-runs/${run.id}/artifacts/${artifact.id}/retry-deletion`,{method:'POST',csrf:a.csrf})).response.status,200);assert.equal((await a.client.request(`/v1/classification-runs/${run.id}/artifacts/${artifact.id}/retry-deletion`,{method:'POST',csrf:a.csrf})).response.status,404);});
test('cross-organization artifact delete and retry preserve metadata and audit state',async()=>{const a=await createSignedInClient(h.baseUrl,h.prisma,'artifact-org-a');const b=await createSignedInClient(h.baseUrl,h.prisma,'artifact-org-b');const d=await createDocumentFixture(h.prisma,b.organization.id);const run=await createRunFixture(h.prisma,b.organization.id,d.id);const artifact=await createArtifactFixture(h.prisma,b.organization.id,run.id);await h.prisma.artifact.update({where:{id:artifact.id},data:{deletionFailureReason:'prior'}});for(const[m,p]of[['DELETE',''],['POST','/retry-deletion']]as const)assert.equal((await a.client.request(`/v1/classification-runs/${run.id}/artifacts/${artifact.id}${p}`,{method:m,csrf:a.csrf})).response.status,404);assert.ok(await h.prisma.artifact.findUnique({where:{id:artifact.id}}));assert.equal(await h.prisma.auditEvent.count({where:{entityId:artifact.id}}),0);});
test('real local storage driver deletes an actual temporary file',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'substrata-artifact-'));try{await fs.mkdir(path.join(root,'nested'));await fs.writeFile(path.join(root,'nested','artifact.log'),'data');const driver=new LocalStorageDriver(root);assert.equal(await driver.delete('nested/artifact.log'),'deleted');await assert.rejects(fs.stat(path.join(root,'nested','artifact.log')));}finally{await fs.rm(root,{recursive:true,force:true});}});
