import assert from 'node:assert/strict';
import test,{after,before} from 'node:test';
import { createSignedInClient } from './helpers/auth';
import { assertAuditCount } from './helpers/assertions';
import { ControlledRemoteCancellationClient } from './helpers/cancellation';
import { createDocumentFixture,createRunFixture } from './helpers/fixtures';
import { startHarness,stopHarness,type IntegrationHarness } from './helpers/test-server';

const remote=new ControlledRemoteCancellationClient();let h:IntegrationHarness;
before(async()=>{h=await startHarness(undefined,remote)});after(async()=>{await stopHarness(h)});
for(const status of ['queued','running'] as const)test(`${status} local run cancellation persists actor timestamps and audit`,async()=>{const a=await createSignedInClient(h.baseUrl,h.prisma,`cancel-${status}`);const d=await createDocumentFixture(h.prisma,a.organization.id);const run=await createRunFixture(h.prisma,a.organization.id,d.id,{status});const r=await a.client.request(`/v1/classification-runs/${run.id}/cancel`,{method:'POST',csrf:a.csrf});assert.equal(r.response.status,200);assert.equal((r.body as {status:string}).status,'cancelled');const p=await h.prisma.classificationRun.findUniqueOrThrow({where:{id:run.id}});assert.ok(p.cancellationRequestedAt);assert.ok(p.cancelledAt);await assertAuditCount(h.prisma,run.id,'classification_run.cancelled',1);});
test('local cancellation requires missing invalid and valid CSRF coverage',async()=>{const a=await createSignedInClient(h.baseUrl,h.prisma,'cancel-csrf');const d=await createDocumentFixture(h.prisma,a.organization.id);const run=await createRunFixture(h.prisma,a.organization.id,d.id,{status:'queued'});for(const csrf of [undefined,'invalid-token-invalid-token'])assert.equal((await a.client.request(`/v1/classification-runs/${run.id}/cancel`,{method:'POST',csrf})).response.status,403);assert.equal((await a.client.request(`/v1/classification-runs/${run.id}/cancel`,{method:'POST',csrf:a.csrf})).response.status,200);});
test('repeated cancellation is idempotent and preserves partial diagnostics',async()=>{const a=await createSignedInClient(h.baseUrl,h.prisma,'cancel-repeat');const d=await createDocumentFixture(h.prisma,a.organization.id);const run=await createRunFixture(h.prisma,a.organization.id,d.id,{status:'running'});await h.prisma.classificationRun.update({where:{id:run.id},data:{validationIssues:{partial:'diagnostic'}}});await a.client.request(`/v1/classification-runs/${run.id}/cancel`,{method:'POST',csrf:a.csrf});assert.equal((await a.client.request(`/v1/classification-runs/${run.id}/cancel`,{method:'POST',csrf:a.csrf})).response.status,200);assert.deepEqual((await h.prisma.classificationRun.findUniqueOrThrow({where:{id:run.id}})).validationIssues,{partial:'diagnostic'});await assertAuditCount(h.prisma,run.id,'classification_run.cancelled',1);});
for(const status of ['completed','failed'] as const)test(`${status} run is not converted to cancelled`,async()=>{const a=await createSignedInClient(h.baseUrl,h.prisma,`cancel-terminal-${status}`);const d=await createDocumentFixture(h.prisma,a.organization.id);const run=await createRunFixture(h.prisma,a.organization.id,d.id,{status});assert.equal((await a.client.request(`/v1/classification-runs/${run.id}/cancel`,{method:'POST',csrf:a.csrf})).response.status,409);assert.equal((await h.prisma.classificationRun.findUniqueOrThrow({where:{id:run.id}})).status,status);});
test('archived active run is not incorrectly cancelled',async()=>{const a=await createSignedInClient(h.baseUrl,h.prisma,'cancel-archived');const d=await createDocumentFixture(h.prisma,a.organization.id);const run=await createRunFixture(h.prisma,a.organization.id,d.id,{status:'running',archived:true});const r=await a.client.request(`/v1/classification-runs/${run.id}/cancel`,{method:'POST',csrf:a.csrf});assert.equal(r.response.status,409);assert.equal((await h.prisma.classificationRun.findUniqueOrThrow({where:{id:run.id}})).status,'running');});
for(const outcome of ['timeout','rejected','unknown_job','unresolved'] as const)test(`remote cancellation ${outcome} returns 409 without false success`,async()=>{remote.enqueue(outcome);const a=await createSignedInClient(h.baseUrl,h.prisma,`remote-${outcome}`);const d=await createDocumentFixture(h.prisma,a.organization.id);const run=await createRunFixture(h.prisma,a.organization.id,d.id,{status:'running',externalJobId:`persisted-${outcome}`});const r=await a.client.request(`/v1/classification-runs/${run.id}/cancel`,{method:'POST',csrf:a.csrf,json:{externalJobId:'client-evil'}});assert.equal(r.response.status,409);assert.notEqual((r.body as {status?:string}).status,'cancelled');const p=await h.prisma.classificationRun.findUniqueOrThrow({where:{id:run.id}});assert.equal(p.status,'running');assert.equal(p.cancelledAt,null);assert.ok(p.cancellationFailureReason);assert.equal(remote.jobIds.at(-1),`persisted-${outcome}`);await assertAuditCount(h.prisma,run.id,'classification_run.cancellation_failed',1);await assertAuditCount(h.prisma,run.id,'classification_run.cancelled',0);});
test('repeated unresolved remote cancellation is safe',async()=>{remote.enqueue('unresolved');remote.enqueue('unresolved');const a=await createSignedInClient(h.baseUrl,h.prisma,'remote-repeat');const d=await createDocumentFixture(h.prisma,a.organization.id);const run=await createRunFixture(h.prisma,a.organization.id,d.id,{status:'running',externalJobId:'repeat-job'});for(let i=0;i<2;i++)assert.equal((await a.client.request(`/v1/classification-runs/${run.id}/cancel`,{method:'POST',csrf:a.csrf})).response.status,409);assert.equal((await h.prisma.classificationRun.findUniqueOrThrow({where:{id:run.id}})).status,'running');await assertAuditCount(h.prisma,run.id,'classification_run.cancellation_failed',2);});
test('cross-organization cancellation is non-disclosing and unchanged',async()=>{const a=await createSignedInClient(h.baseUrl,h.prisma,'cancel-org-a');const b=await createSignedInClient(h.baseUrl,h.prisma,'cancel-org-b');const d=await createDocumentFixture(h.prisma,b.organization.id);const run=await createRunFixture(h.prisma,b.organization.id,d.id,{status:'queued'});assert.equal((await a.client.request(`/v1/classification-runs/${run.id}/cancel`,{method:'POST',csrf:a.csrf})).response.status,404);assert.equal((await h.prisma.classificationRun.findUniqueOrThrow({where:{id:run.id}})).status,'queued');assert.equal(await h.prisma.auditEvent.count({where:{entityId:run.id}}),0);});
