import assert from 'node:assert/strict';
import test, { after, before } from 'node:test';
import { createSignedInClient } from './helpers/auth';
import { assertAuditCount } from './helpers/assertions';
import { createArtifactFixture, createDocumentFixture, createRunFixture } from './helpers/fixtures';
import { ControlledStorageDriver } from './helpers/storage';
import { startHarness, stopHarness, type IntegrationHarness } from './helpers/test-server';

const storage = new ControlledStorageDriver(); let h: IntegrationHarness;
before(async () => { h = await startHarness(storage); }); after(async () => { await stopHarness(h); });

for (const [name, query, expected] of [['default','',1],['active','?lifecycle=active',1],['archived','?lifecycle=archived',1],['all','?lifecycle=all',2]] as const) test(`run listing ${name} returns expected lifecycle records`, async () => {
  const a = await createSignedInClient(h.baseUrl,h.prisma,`run-list-${name}`); const d = await createDocumentFixture(h.prisma,a.organization.id); await createRunFixture(h.prisma,a.organization.id,d.id); await createRunFixture(h.prisma,a.organization.id,d.id,{archived:true}); const r=await a.client.request(`/v1/classification-runs${query}`); assert.equal(r.response.status,200); assert.equal((r.body as unknown[]).length,expected); for (const item of r.body as Array<Record<string, unknown>>) { assert.equal('extractedTextPath' in item, false); assert.equal('structuredOutputPath' in item, false); assert.equal('memoArtifactPath' in item, false); assert.equal('storagePath' in (item.document as Record<string, unknown>), false); }
});
test('run listing rejects invalid lifecycle', async()=>{const a=await createSignedInClient(h.baseUrl,h.prisma,'run-invalid');assert.equal((await a.client.request('/v1/classification-runs?lifecycle=bad')).response.status,400);});
for (const status of ['completed','failed'] as const) test(`${status} terminal run can be archived with audit and idempotence`,async()=>{const a=await createSignedInClient(h.baseUrl,h.prisma,`archive-${status}`);const d=await createDocumentFixture(h.prisma,a.organization.id);const run=await createRunFixture(h.prisma,a.organization.id,d.id,{status});for(const csrf of [undefined,'invalid-token-invalid-token'])assert.equal((await a.client.request(`/v1/classification-runs/${run.id}/archive`,{method:'POST',csrf})).response.status,403);assert.equal((await a.client.request(`/v1/classification-runs/${run.id}/archive`,{method:'POST',csrf:a.csrf})).response.status,200);const p=await h.prisma.classificationRun.findUniqueOrThrow({where:{id:run.id}});assert.ok(p.archivedAt);assert.equal(p.archivedByUserId,a.user.id);assert.equal((await a.client.request(`/v1/classification-runs/${run.id}/archive`,{method:'POST',csrf:a.csrf})).response.status,200);await assertAuditCount(h.prisma,run.id,'classification_run.archived',1);});
for(const status of ['queued','running'] as const)test(`${status} run cannot be archived`,async()=>{const a=await createSignedInClient(h.baseUrl,h.prisma,`no-archive-${status}`);const d=await createDocumentFixture(h.prisma,a.organization.id);const run=await createRunFixture(h.prisma,a.organization.id,d.id,{status});assert.equal((await a.client.request(`/v1/classification-runs/${run.id}/archive`,{method:'POST',csrf:a.csrf})).response.status,409);assert.equal((await h.prisma.classificationRun.findUniqueOrThrow({where:{id:run.id}})).archivedAt,null);});
test('archived run restores, clears actor, audits, and is idempotent',async()=>{const a=await createSignedInClient(h.baseUrl,h.prisma,'run-restore');const d=await createDocumentFixture(h.prisma,a.organization.id);const run=await createRunFixture(h.prisma,a.organization.id,d.id,{archived:true});for(const csrf of [undefined,'invalid-token-invalid-token'])assert.equal((await a.client.request(`/v1/classification-runs/${run.id}/restore`,{method:'POST',csrf})).response.status,403);assert.equal((await a.client.request(`/v1/classification-runs/${run.id}/restore`,{method:'POST',csrf:a.csrf})).response.status,200);const p=await h.prisma.classificationRun.findUniqueOrThrow({where:{id:run.id}});assert.equal(p.archivedAt,null);assert.equal(p.archivedByUserId,null);await a.client.request(`/v1/classification-runs/${run.id}/restore`,{method:'POST',csrf:a.csrf});await assertAuditCount(h.prisma,run.id,'classification_run.restored',1);});
for(const [label,archived,status,confirmation,expected] of [['active',false,'completed','id',409],['non-terminal',true,'running','id',409],['wrong confirmation',true,'completed','wrong',400]] as const)test(`run permanent deletion rejects ${label}`,async()=>{const a=await createSignedInClient(h.baseUrl,h.prisma,`run-delete-${label}`);const d=await createDocumentFixture(h.prisma,a.organization.id);const run=await createRunFixture(h.prisma,a.organization.id,d.id,{archived,status});const r=await a.client.request(`/v1/classification-runs/${run.id}/permanent`,{method:'DELETE',csrf:a.csrf,json:{confirmation:confirmation==='id'?run.id:confirmation}});assert.equal(r.response.status,expected);assert.ok(await h.prisma.classificationRun.findUnique({where:{id:run.id}}));});
test('run permanent deletion requires admin and real CSRF',async()=>{const a=await createSignedInClient(h.baseUrl,h.prisma,'run-delete-csrf');const d=await createDocumentFixture(h.prisma,a.organization.id);const run=await createRunFixture(h.prisma,a.organization.id,d.id,{archived:true});for(const csrf of [undefined,'invalid-token-invalid-token'])assert.equal((await a.client.request(`/v1/classification-runs/${run.id}/permanent`,{method:'DELETE',csrf,json:{confirmation:run.id}})).response.status,403);const v=await createSignedInClient(h.baseUrl,h.prisma,'run-delete-viewer','VIEWER');const vd=await createDocumentFixture(h.prisma,v.organization.id);const vr=await createRunFixture(h.prisma,v.organization.id,vd.id,{archived:true});assert.equal((await v.client.request(`/v1/classification-runs/${vr.id}/permanent`,{method:'DELETE',csrf:v.csrf,json:{confirmation:vr.id}})).response.status,403);});
test('run deletion cascades selected derived data and artifacts but preserves parent and sibling',async()=>{const a=await createSignedInClient(h.baseUrl,h.prisma,'run-delete-success');const d=await createDocumentFixture(h.prisma,a.organization.id);const run=await createRunFixture(h.prisma,a.organization.id,d.id,{archived:true});const sibling=await createRunFixture(h.prisma,a.organization.id,d.id);await createArtifactFixture(h.prisma,a.organization.id,run.id,'persisted/run.log');await h.prisma.reviewMemo.create({data:{organizationId:a.organization.id,classificationRunId:run.id,contentMarkdown:'memo'}});const r=await a.client.request(`/v1/classification-runs/${run.id}/permanent`,{method:'DELETE',csrf:a.csrf,json:{confirmation:run.id,storagePath:'evil'}});assert.equal(r.response.status,200);assert.deepEqual(Object.keys(r.body as object).sort(),['cleanup','id']);assert.equal(await h.prisma.classificationRun.findUnique({where:{id:run.id}}),null);assert.ok(await h.prisma.document.findUnique({where:{id:d.id}}));assert.ok(await h.prisma.classificationRun.findUnique({where:{id:sibling.id}}));assert.ok(storage.attempts.includes('persisted/run.log'));assert.ok(!storage.attempts.includes('evil'));await assertAuditCount(h.prisma,run.id,'classification_run.permanently_deleted',1);});
for(const outcome of ['timeout','permission_denied','unknown'] as const)test(`run artifact cleanup ${outcome} prevents false success`,async()=>{storage.enqueue(outcome);const a=await createSignedInClient(h.baseUrl,h.prisma,`run-fail-${outcome}`);const d=await createDocumentFixture(h.prisma,a.organization.id);const run=await createRunFixture(h.prisma,a.organization.id,d.id,{archived:true});await createArtifactFixture(h.prisma,a.organization.id,run.id);const r=await a.client.request(`/v1/classification-runs/${run.id}/permanent`,{method:'DELETE',csrf:a.csrf,json:{confirmation:run.id}});assert.notEqual(r.response.status,200);assert.ok(await h.prisma.classificationRun.findUnique({where:{id:run.id}}));await assertAuditCount(h.prisma,run.id,'classification_run.deletion_failed',1);});
test('cross-organization run list and mutations are non-disclosing',async()=>{const a=await createSignedInClient(h.baseUrl,h.prisma,'run-org-a');const b=await createSignedInClient(h.baseUrl,h.prisma,'run-org-b');const d=await createDocumentFixture(h.prisma,b.organization.id);const run=await createRunFixture(h.prisma,b.organization.id,d.id,{archived:true});assert.ok(!((await a.client.request('/v1/classification-runs?lifecycle=all')).body as {id:string}[]).some(x=>x.id===run.id));for(const [method,path,json] of [['POST','archive',undefined],['POST','restore',undefined],['DELETE','permanent',{confirmation:run.id}]] as const)assert.equal((await a.client.request(`/v1/classification-runs/${run.id}/${path}`,{method,csrf:a.csrf,json})).response.status,404);assert.ok(await h.prisma.classificationRun.findUnique({where:{id:run.id}}));assert.equal(await h.prisma.auditEvent.count({where:{entityId:run.id}}),0);});
